namespace Santex_Football.Application.Tests.Services
{
    public static class FakeApiResponse
    {
        public static string Competitions = "[\r\n    {\r\n        \"_links\": {\r\n            \"self\": {\r\n                \"href\": \"http://api.football-data.org/v1/competitions/444\"\r\n            },\r\n            \"teams\": {\r\n                \"href\": \"http://api.football-data.org/v1/competitions/444/teams\"\r\n            },\r\n            \"fixtures\": {\r\n                \"href\": \"http://api.football-data.org/v1/competitions/444/fixtures\"\r\n            },\r\n            \"leagueTable\": {\r\n                \"href\": \"http://api.football-data.org/v1/competitions/444/leagueTable\"\r\n            }\r\n        },\r\n        \"id\": 444,\r\n        \"caption\": \"Campeonato Brasileiro da Série A\",\r\n        \"league\": \"BSA\",\r\n        \"year\": \"2017\",\r\n        \"currentMatchday\": 38,\r\n        \"numberOfMatchdays\": 38,\r\n        \"numberOfTeams\": 20,\r\n        \"numberOfGames\": 380,\r\n        \"lastUpdated\": \"2017-12-11T07:05:27Z\"\r\n    }\r\n]";

        public static string Teams =
            "{\r\n    \"_links\": {\r\n        \"self\": {\r\n            \"href\": \"http://api.football-data.org/v1/competitions/444/teams\"\r\n        },\r\n        \"competition\": {\r\n            \"href\": \"http://api.football-data.org/v1/competitions/444\"\r\n        }\r\n    },\r\n    \"count\": 1,\r\n    \"teams\": [\r\n        {\r\n            \"_links\": {\r\n                \"self\": {\r\n                    \"href\": \"http://api.football-data.org/v1/teams/1783\"\r\n                },\r\n                \"fixtures\": {\r\n                    \"href\": \"http://api.football-data.org/v1/teams/1783/fixtures\"\r\n                },\r\n                \"players\": {\r\n                    \"href\": \"http://api.football-data.org/v1/teams/1783/players\"\r\n                }\r\n            },\r\n            \"name\": \"CR Flamengo\",\r\n            \"code\": null,\r\n            \"shortName\": \"Flamengo\",\r\n            \"squadMarketValue\": null,\r\n            \"crestUrl\": \"https://upload.wikimedia.org/wikipedia/en/c/c9/Flamengo_logo.svg\"\r\n        }\r\n    ]\r\n}";

        public static string Players =
            "{\r\n    \"_links\": {\r\n        \"self\": {\r\n            \"href\": \"http://api.football-data.org/v1/teams/66/players\"\r\n        },\r\n        \"team\": {\r\n            \"href\": \"http://api.football-data.org/v1/teams/66\"\r\n        }\r\n    },\r\n    \"count\": 1,\r\n    \"players\": [\r\n        {\r\n            \"name\": \"Sergio Romero\",\r\n            \"position\": \"Keeper\",\r\n            \"jerseyNumber\": 20,\r\n            \"dateOfBirth\": \"1987-02-22\",\r\n            \"nationality\": \"Argentina\",\r\n            \"contractUntil\": \"2021-06-30\",\r\n            \"marketValue\": null\r\n        },        \r\n    ]\r\n}";
    }
}